BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

CREATE TABLE IF NOT EXISTS tapes (
    tape_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    volume_label   TEXT        NOT NULL UNIQUE,
    date_formatted TIMESTAMPTZ,
    total_capacity BIGINT,
    used_space     BIGINT      NOT NULL DEFAULT 0 CHECK (used_space >= 0)
);

CREATE TABLE IF NOT EXISTS catalog_directories (
    directory_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tape_label      TEXT   NOT NULL
        REFERENCES tapes(volume_label) ON UPDATE CASCADE ON DELETE CASCADE,
    parent_id       BIGINT REFERENCES catalog_directories(directory_id)
        ON DELETE CASCADE,
    name            TEXT   NOT NULL,
    normalized_path TEXT   NOT NULL,
    UNIQUE (tape_label, normalized_path)
);

CREATE TABLE IF NOT EXISTS archive_bundles (
    bundle_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tape_label TEXT NOT NULL
        REFERENCES tapes(volume_label) ON UPDATE CASCADE ON DELETE CASCADE,
    tape_path  TEXT NOT NULL,
    UNIQUE (tape_label, tape_path)
);

CREATE TABLE IF NOT EXISTS archive_runs (
    run_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_label         TEXT NOT NULL,
    tape_label        TEXT NOT NULL REFERENCES tapes(volume_label)
        ON UPDATE CASCADE,
    session_kind      TEXT NOT NULL DEFAULT 'legacy'
        CHECK (session_kind IN ('legacy','local','remote')),
    -- Typed, foreign-keyed session references (replaces the old FK-less
    -- polymorphic `session_id`). The FKs and the kind-consistency CHECK are
    -- attached by scripts/sql/004_postgres_archive_runs_sessions.sql, which
    -- runs after local_sessions/remote_sessions exist and also migrates any
    -- existing database off the legacy column.
    local_session_id  BIGINT,
    remote_session_id BIGINT,
    started_at        TIMESTAMPTZ NOT NULL,
    completed_at      TIMESTAMPTZ,
    UNIQUE (run_label, tape_label)
);

CREATE TABLE IF NOT EXISTS local_sessions (
    session_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_label TEXT NOT NULL,
    source_dir    TEXT NOT NULL,
    total_chunks  INTEGER NOT NULL CHECK (total_chunks >= 0),
    backup_mode   TEXT NOT NULL DEFAULT 'auto'
        CHECK (backup_mode IN ('auto','direct','pack')),
    created_at    TIMESTAMPTZ NOT NULL,
    completed_at  TIMESTAMPTZ,
    status        TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active','completed','abandoned'))
);

CREATE TABLE IF NOT EXISTS local_chunks_manifest (
    manifest_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id     BIGINT NOT NULL REFERENCES local_sessions(session_id)
        ON DELETE CASCADE,
    chunk_index    INTEGER NOT NULL CHECK (chunk_index >= 0),
    top_level_dir  TEXT NOT NULL,
    dir_size_bytes BIGINT NOT NULL CHECK (dir_size_bytes >= 0),
    status         TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','staged','backed_up')),
    tape_label     TEXT REFERENCES tapes(volume_label)
        ON UPDATE CASCADE ON DELETE SET NULL,
    started_at     TIMESTAMPTZ,
    completed_at   TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS remote_snapshots (
    snapshot_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remote_host  TEXT NOT NULL,
    remote_path  TEXT NOT NULL,
    fingerprint  BYTEA NOT NULL UNIQUE,
    total_files  BIGINT NOT NULL CHECK (total_files >= 0),
    total_bytes  BIGINT NOT NULL CHECK (total_bytes >= 0),
    created_at   TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS remote_snapshot_files (
    snapshot_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id      BIGINT NOT NULL REFERENCES remote_snapshots(snapshot_id)
        ON DELETE CASCADE,
    remote_path      TEXT NOT NULL,
    file_size_bytes  BIGINT NOT NULL CHECK (file_size_bytes >= 0),
    UNIQUE (snapshot_id, remote_path)
);

CREATE TABLE IF NOT EXISTS remote_plans (
    plan_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id  BIGINT NOT NULL REFERENCES remote_snapshots(snapshot_id)
        ON DELETE CASCADE,
    fingerprint  BYTEA NOT NULL UNIQUE,
    chunk_count  INTEGER NOT NULL CHECK (chunk_count >= 0),
    created_at   TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS remote_sessions (
    session_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_label TEXT NOT NULL,
    remote_host   TEXT NOT NULL,
    remote_user   TEXT NOT NULL,
    remote_path   TEXT NOT NULL,
    tape_label    TEXT NOT NULL REFERENCES tapes(volume_label)
        ON UPDATE CASCADE ON DELETE CASCADE,
    staging_dir   TEXT NOT NULL,
    total_files   BIGINT DEFAULT 0 CHECK (total_files >= 0),
    total_bytes   BIGINT DEFAULT 0 CHECK (total_bytes >= 0),
    chunk_count   INTEGER DEFAULT 0 CHECK (chunk_count >= 0),
    plan_id       BIGINT REFERENCES remote_plans(plan_id),
    created_at    TIMESTAMPTZ NOT NULL,
    completed_at  TIMESTAMPTZ,
    status        TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active','completed','abandoned'))
);

CREATE TABLE IF NOT EXISTS remote_plan_files (
    plan_file_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id          BIGINT NOT NULL REFERENCES remote_plans(plan_id)
        ON DELETE CASCADE,
    snapshot_file_id BIGINT NOT NULL REFERENCES remote_snapshot_files(snapshot_file_id),
    chunk_index      INTEGER NOT NULL CHECK (chunk_index >= 0),
    ordinal          INTEGER NOT NULL CHECK (ordinal >= 0),
    UNIQUE (plan_id, snapshot_file_id)
);

CREATE TABLE IF NOT EXISTS remote_chunks (
    session_id  BIGINT NOT NULL REFERENCES remote_sessions(session_id)
        ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL CHECK (chunk_index >= 0),
    status      TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','fetching','packing','backing','done',
                          'fetch_failed','backup_failed')),
    error_msg   TEXT,
    updated_at  TIMESTAMPTZ,
    PRIMARY KEY (session_id, chunk_index)
);

CREATE TABLE IF NOT EXISTS remote_file_state (
    session_id     BIGINT NOT NULL REFERENCES remote_sessions(session_id)
        ON DELETE CASCADE,
    plan_file_id   BIGINT NOT NULL REFERENCES remote_plan_files(plan_file_id),
    status         TEXT
        CHECK (status IS NULL OR status IN
               ('pending','fetching','fetched','fetch_failed','source_missing')),
    local_rel_path TEXT,
    error_msg      TEXT,
    updated_at     TIMESTAMPTZ,
    PRIMARY KEY (session_id, plan_file_id)
);

CREATE TABLE IF NOT EXISTS files_index (
    file_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_path       TEXT    NOT NULL,
    file_size_bytes     BIGINT  NOT NULL CHECK (file_size_bytes >= 0),
    tape_label          TEXT    NOT NULL REFERENCES tapes(volume_label)
        ON UPDATE CASCADE,
    source_host         TEXT    NOT NULL DEFAULT 'so02',
    is_packed           BOOLEAN NOT NULL DEFAULT FALSE,
    stored_path         TEXT    NOT NULL,
    local_session_id    BIGINT  REFERENCES local_sessions(session_id),
    local_chunk_index   INTEGER,
    bundle_id           BIGINT  REFERENCES archive_bundles(bundle_id),
    record_key          BYTEA   NOT NULL CHECK (octet_length(record_key) = 32),
    archive_run_id      BIGINT  NOT NULL REFERENCES archive_runs(run_id),
    directory_id        BIGINT  NOT NULL REFERENCES catalog_directories(directory_id),
    catalog_name        TEXT    NOT NULL,
    catalog_backup_date TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_packed_has_bundle CHECK (NOT is_packed OR bundle_id IS NOT NULL)
);

COMMIT;
