BEGIN;

CREATE TABLE IF NOT EXISTS directory_archive_stats (
    stat_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_host          TEXT NOT NULL,
    original_dir_path    TEXT NOT NULL,
    tape_label           TEXT NOT NULL REFERENCES tapes(volume_label)
        ON UPDATE CASCADE ON DELETE CASCADE,
    archive_run_id       BIGINT REFERENCES archive_runs(run_id)
        ON DELETE SET NULL,
    local_session_id     BIGINT REFERENCES local_sessions(session_id)
        ON DELETE SET NULL,
    remote_session_id    BIGINT REFERENCES remote_sessions(session_id)
        ON DELETE SET NULL,
    chunk_index          INTEGER,
    stored_root_path     TEXT,
    direct_file_count    BIGINT NOT NULL CHECK (direct_file_count >= 0),
    direct_bytes         BIGINT NOT NULL CHECK (direct_bytes >= 0),
    recursive_file_count BIGINT NOT NULL CHECK (recursive_file_count >= 0),
    recursive_bytes      BIGINT NOT NULL CHECK (recursive_bytes >= 0),
    small_file_count     BIGINT NOT NULL CHECK (small_file_count >= 0),
    small_file_bytes     BIGINT NOT NULL CHECK (small_file_bytes >= 0),
    large_file_count     BIGINT NOT NULL CHECK (large_file_count >= 0),
    large_file_bytes     BIGINT NOT NULL CHECK (large_file_bytes >= 0),
    packed_bundle_count  BIGINT NOT NULL CHECK (packed_bundle_count >= 0),
    backup_date          TIMESTAMPTZ NOT NULL,
    record_key           BYTEA NOT NULL CHECK (octet_length(record_key) = 32),
    UNIQUE(record_key)
);

CREATE TABLE IF NOT EXISTS directory_archive_bundles (
    bundle_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_host           TEXT NOT NULL,
    original_dir_path     TEXT NOT NULL,
    tape_label            TEXT NOT NULL REFERENCES tapes(volume_label)
        ON UPDATE CASCADE ON DELETE CASCADE,
    archive_run_id        BIGINT REFERENCES archive_runs(run_id)
        ON DELETE SET NULL,
    local_session_id      BIGINT REFERENCES local_sessions(session_id)
        ON DELETE SET NULL,
    remote_session_id     BIGINT REFERENCES remote_sessions(session_id)
        ON DELETE SET NULL,
    chunk_index           INTEGER,
    stored_bundle_path    TEXT NOT NULL,
    manifest_path         TEXT,
    manifest_format       TEXT,
    manifest_compression  TEXT,
    file_count            BIGINT NOT NULL CHECK (file_count >= 0),
    byte_count            BIGINT NOT NULL CHECK (byte_count >= 0),
    small_file_count      BIGINT NOT NULL CHECK (small_file_count >= 0),
    small_file_bytes      BIGINT NOT NULL CHECK (small_file_bytes >= 0),
    large_file_count      BIGINT NOT NULL CHECK (large_file_count >= 0),
    large_file_bytes      BIGINT NOT NULL CHECK (large_file_bytes >= 0),
    backup_date           TIMESTAMPTZ NOT NULL,
    record_key            BYTEA NOT NULL CHECK (octet_length(record_key) = 32),
    UNIQUE(record_key)
);

CREATE TABLE IF NOT EXISTS directory_tree_index (
    dir_id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_host                       TEXT NOT NULL,
    original_dir_path                 TEXT NOT NULL,
    parent_original_dir_path          TEXT,
    dir_name                          TEXT NOT NULL,
    depth                             INTEGER NOT NULL CHECK (depth >= 0),
    tape_label                        TEXT NOT NULL REFERENCES tapes(volume_label)
        ON UPDATE CASCADE ON DELETE CASCADE,
    archive_run_id                    BIGINT REFERENCES archive_runs(run_id)
        ON DELETE SET NULL,
    local_session_id                  BIGINT REFERENCES local_sessions(session_id)
        ON DELETE SET NULL,
    remote_session_id                 BIGINT REFERENCES remote_sessions(session_id)
        ON DELETE SET NULL,
    chunk_index                       INTEGER,
    bundle_id                         BIGINT REFERENCES directory_archive_bundles(bundle_id)
        ON DELETE SET NULL,
    stored_bundle_path                TEXT,
    manifest_path                     TEXT,
    direct_file_count                 BIGINT NOT NULL CHECK (direct_file_count >= 0),
    direct_bytes                      BIGINT NOT NULL CHECK (direct_bytes >= 0),
    recursive_file_count              BIGINT NOT NULL CHECK (recursive_file_count >= 0),
    recursive_bytes                   BIGINT NOT NULL CHECK (recursive_bytes >= 0),
    direct_small_file_count           BIGINT NOT NULL CHECK (direct_small_file_count >= 0),
    direct_small_file_bytes           BIGINT NOT NULL CHECK (direct_small_file_bytes >= 0),
    recursive_small_file_count        BIGINT NOT NULL CHECK (recursive_small_file_count >= 0),
    recursive_small_file_bytes        BIGINT NOT NULL CHECK (recursive_small_file_bytes >= 0),
    direct_large_file_count           BIGINT NOT NULL CHECK (direct_large_file_count >= 0),
    direct_large_file_bytes           BIGINT NOT NULL CHECK (direct_large_file_bytes >= 0),
    recursive_large_file_count        BIGINT NOT NULL CHECK (recursive_large_file_count >= 0),
    recursive_large_file_bytes        BIGINT NOT NULL CHECK (recursive_large_file_bytes >= 0),
    backup_date                       TIMESTAMPTZ NOT NULL,
    record_key                        BYTEA NOT NULL CHECK (octet_length(record_key) = 32),
    UNIQUE(record_key)
);

CREATE INDEX IF NOT EXISTS idx_directory_stats_tape_path
    ON directory_archive_stats(tape_label, source_host, original_dir_path);

CREATE INDEX IF NOT EXISTS idx_directory_bundles_tape_path
    ON directory_archive_bundles(tape_label, source_host, original_dir_path);

CREATE INDEX IF NOT EXISTS idx_directory_bundles_manifest
    ON directory_archive_bundles(manifest_path)
    WHERE manifest_path IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_directory_tree_parent
    ON directory_tree_index(tape_label, source_host, parent_original_dir_path, dir_name);

CREATE INDEX IF NOT EXISTS idx_directory_tree_path
    ON directory_tree_index(source_host, tape_label, original_dir_path);

CREATE INDEX IF NOT EXISTS idx_directory_tree_bundle
    ON directory_tree_index(bundle_id)
    WHERE bundle_id IS NOT NULL;

-- find_directory_tree() matches original_dir_path with ILIKE '%term%'. The
-- btree indexes above only accelerate anchored prefixes, so add a trigram GIN
-- for arbitrary substring search. Keep the build below Docker's /dev/shm
-- ceiling so PostgreSQL spills to temp files instead of hitting a hard limit.
SET LOCAL maintenance_work_mem = '512MB';

CREATE INDEX IF NOT EXISTS idx_directory_tree_path_trgm
    ON directory_tree_index USING gin (original_dir_path gin_trgm_ops);

RESET maintenance_work_mem;

-- Bundle/tape consistency for the directory catalog: a directory row must
-- reference a bundle on the same tape. bundle_id is the PK of
-- directory_archive_bundles, so the composite UNIQUE cannot fail on existing
-- data. The FK is NOT VALID (enforced for new/updated rows; legacy rows are
-- not scanned) and MATCH SIMPLE skips NULL bundle_id rows.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_dir_bundles_id_tape'
          AND conrelid = 'directory_archive_bundles'::regclass
    ) THEN
        ALTER TABLE directory_archive_bundles
            ADD CONSTRAINT uq_dir_bundles_id_tape UNIQUE (bundle_id, tape_label);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_dir_tree_bundle_tape'
          AND conrelid = 'directory_tree_index'::regclass
    ) THEN
        -- Default ON DELETE NO ACTION (deferred check at statement end). The
        -- sibling single-column FK on bundle_id already runs ON DELETE SET
        -- NULL, so by the time this composite constraint is checked bundle_id
        -- is NULL and MATCH SIMPLE skips it -- deletes are not blocked. It
        -- cannot use SET NULL itself because tape_label is NOT NULL.
        ALTER TABLE directory_tree_index
            ADD CONSTRAINT fk_dir_tree_bundle_tape
            FOREIGN KEY (bundle_id, tape_label)
            REFERENCES directory_archive_bundles (bundle_id, tape_label)
            ON UPDATE CASCADE
            NOT VALID;
    END IF;
END $$;

COMMIT;
