BEGIN;

CREATE TABLE IF NOT EXISTS directory_archive_stats (
    stat_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_host          TEXT NOT NULL,
    original_dir_path    TEXT NOT NULL,
    tape_label           TEXT NOT NULL REFERENCES tapes(volume_label)
        ON UPDATE CASCADE ON DELETE CASCADE,
    archive_run_id       BIGINT REFERENCES archive_runs(run_id)
        ON DELETE SET NULL,
    local_session_id     BIGINT REFERENCES local_sessions(session_id)
        ON DELETE SET NULL,
    remote_session_id    BIGINT REFERENCES remote_sessions(session_id)
        ON DELETE SET NULL,
    chunk_index          INTEGER,
    stored_root_path     TEXT,
    direct_file_count    BIGINT NOT NULL CHECK (direct_file_count >= 0),
    direct_bytes         BIGINT NOT NULL CHECK (direct_bytes >= 0),
    recursive_file_count BIGINT NOT NULL CHECK (recursive_file_count >= 0),
    recursive_bytes      BIGINT NOT NULL CHECK (recursive_bytes >= 0),
    small_file_count     BIGINT NOT NULL CHECK (small_file_count >= 0),
    small_file_bytes     BIGINT NOT NULL CHECK (small_file_bytes >= 0),
    large_file_count     BIGINT NOT NULL CHECK (large_file_count >= 0),
    large_file_bytes     BIGINT NOT NULL CHECK (large_file_bytes >= 0),
    packed_bundle_count  BIGINT NOT NULL CHECK (packed_bundle_count >= 0),
    backup_date          TIMESTAMPTZ NOT NULL,
    record_key           BYTEA NOT NULL CHECK (octet_length(record_key) = 32),
    UNIQUE(record_key)
);

CREATE TABLE IF NOT EXISTS directory_archive_bundles (
    bundle_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_host           TEXT NOT NULL,
    original_dir_path     TEXT NOT NULL,
    tape_label            TEXT NOT NULL REFERENCES tapes(volume_label)
        ON UPDATE CASCADE ON DELETE CASCADE,
    archive_run_id        BIGINT REFERENCES archive_runs(run_id)
        ON DELETE SET NULL,
    local_session_id      BIGINT REFERENCES local_sessions(session_id)
        ON DELETE SET NULL,
    remote_session_id     BIGINT REFERENCES remote_sessions(session_id)
        ON DELETE SET NULL,
    chunk_index           INTEGER,
    stored_bundle_path    TEXT NOT NULL,
    manifest_path         TEXT,
    manifest_format       TEXT,
    manifest_compression  TEXT,
    file_count            BIGINT NOT NULL CHECK (file_count >= 0),
    byte_count            BIGINT NOT NULL CHECK (byte_count >= 0),
    small_file_count      BIGINT NOT NULL CHECK (small_file_count >= 0),
    small_file_bytes      BIGINT NOT NULL CHECK (small_file_bytes >= 0),
    large_file_count      BIGINT NOT NULL CHECK (large_file_count >= 0),
    large_file_bytes      BIGINT NOT NULL CHECK (large_file_bytes >= 0),
    backup_date           TIMESTAMPTZ NOT NULL,
    record_key            BYTEA NOT NULL CHECK (octet_length(record_key) = 32),
    UNIQUE(record_key)
);

CREATE TABLE IF NOT EXISTS directory_tree_index (
    dir_id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_host                       TEXT NOT NULL,
    original_dir_path                 TEXT NOT NULL,
    parent_original_dir_path          TEXT,
    dir_name                          TEXT NOT NULL,
    depth                             INTEGER NOT NULL CHECK (depth >= 0),
    tape_label                        TEXT NOT NULL REFERENCES tapes(volume_label)
        ON UPDATE CASCADE ON DELETE CASCADE,
    archive_run_id                    BIGINT REFERENCES archive_runs(run_id)
        ON DELETE SET NULL,
    local_session_id                  BIGINT REFERENCES local_sessions(session_id)
        ON DELETE SET NULL,
    remote_session_id                 BIGINT REFERENCES remote_sessions(session_id)
        ON DELETE SET NULL,
    chunk_index                       INTEGER,
    bundle_id                         BIGINT REFERENCES directory_archive_bundles(bundle_id)
        ON DELETE SET NULL,
    stored_bundle_path                TEXT,
    manifest_path                     TEXT,
    direct_file_count                 BIGINT NOT NULL CHECK (direct_file_count >= 0),
    direct_bytes                      BIGINT NOT NULL CHECK (direct_bytes >= 0),
    recursive_file_count              BIGINT NOT NULL CHECK (recursive_file_count >= 0),
    recursive_bytes                   BIGINT NOT NULL CHECK (recursive_bytes >= 0),
    direct_small_file_count           BIGINT NOT NULL CHECK (direct_small_file_count >= 0),
    direct_small_file_bytes           BIGINT NOT NULL CHECK (direct_small_file_bytes >= 0),
    recursive_small_file_count        BIGINT NOT NULL CHECK (recursive_small_file_count >= 0),
    recursive_small_file_bytes        BIGINT NOT NULL CHECK (recursive_small_file_bytes >= 0),
    direct_large_file_count           BIGINT NOT NULL CHECK (direct_large_file_count >= 0),
    direct_large_file_bytes           BIGINT NOT NULL CHECK (direct_large_file_bytes >= 0),
    recursive_large_file_count        BIGINT NOT NULL CHECK (recursive_large_file_count >= 0),
    recursive_large_file_bytes        BIGINT NOT NULL CHECK (recursive_large_file_bytes >= 0),
    backup_date                       TIMESTAMPTZ NOT NULL,
    record_key                        BYTEA NOT NULL CHECK (octet_length(record_key) = 32),
    UNIQUE(record_key)
);

CREATE INDEX IF NOT EXISTS idx_directory_stats_tape_path
    ON directory_archive_stats(tape_label, source_host, original_dir_path);

CREATE INDEX IF NOT EXISTS idx_directory_bundles_tape_path
    ON directory_archive_bundles(tape_label, source_host, original_dir_path);

CREATE INDEX IF NOT EXISTS idx_directory_bundles_manifest
    ON directory_archive_bundles(manifest_path)
    WHERE manifest_path IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_directory_tree_parent
    ON directory_tree_index(tape_label, source_host, parent_original_dir_path, dir_name);

CREATE INDEX IF NOT EXISTS idx_directory_tree_path
    ON directory_tree_index(source_host, tape_label, original_dir_path);

CREATE INDEX IF NOT EXISTS idx_directory_tree_bundle
    ON directory_tree_index(bundle_id)
    WHERE bundle_id IS NOT NULL;

COMMIT;
