BEGIN;

CREATE TABLE IF NOT EXISTS local_manifest_exports (
    export_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    threshold_bytes        BIGINT NOT NULL CHECK (threshold_bytes > 0),
    archive_root           TEXT NOT NULL,
    hot_backup_path        TEXT NOT NULL,
    status                 TEXT NOT NULL
        CHECK (status IN ('snapshotting','exporting','exported','pruning',
                          'validated','validation_failed','pruned','failed')),
    candidate_rows         BIGINT NOT NULL DEFAULT 0,
    candidate_bytes        BIGINT NOT NULL DEFAULT 0,
    eligible_rows          BIGINT NOT NULL DEFAULT 0,
    eligible_bytes         BIGINT NOT NULL DEFAULT 0,
    skipped_rows           BIGINT NOT NULL DEFAULT 0,
    segment_count          BIGINT NOT NULL DEFAULT 0,
    validation_passed      BOOLEAN NOT NULL DEFAULT FALSE,
    validation_report      JSONB,
    prune_report           JSONB,
    started_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    exported_at            TIMESTAMPTZ,
    validated_at           TIMESTAMPTZ,
    pruned_at              TIMESTAMPTZ,
    error_message          TEXT
);

CREATE TABLE IF NOT EXISTS local_manifest_export_rows (
    export_id                    BIGINT NOT NULL
        REFERENCES local_manifest_exports(export_id) ON DELETE RESTRICT,
    source_file_id               BIGINT NOT NULL,
    source_record_key            BYTEA NOT NULL
        CHECK (octet_length(source_record_key) = 32),
    tape_label                   TEXT NOT NULL,
    source_host                  TEXT NOT NULL,
    original_path                TEXT NOT NULL,
    file_size_bytes              BIGINT NOT NULL CHECK (file_size_bytes >= 0),
    archive_run_id               BIGINT NOT NULL,
    local_session_id             BIGINT,
    remote_session_id            BIGINT,
    chunk_index                  INTEGER,
    bundle_id                    BIGINT,
    covered_by_directory_catalog BOOLEAN NOT NULL DEFAULT FALSE,
    eligible                     BOOLEAN NOT NULL,
    skip_reason                  TEXT,
    manifest_relpath             TEXT,
    pruned_at                    TIMESTAMPTZ,
    PRIMARY KEY (export_id, source_file_id),
    CHECK ((eligible AND skip_reason IS NULL)
        OR (NOT eligible AND skip_reason IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_local_manifest_rows_eligible
    ON local_manifest_export_rows(export_id, eligible, source_file_id);

CREATE INDEX IF NOT EXISTS idx_local_manifest_rows_skip_reason
    ON local_manifest_export_rows(export_id, skip_reason)
    WHERE NOT eligible;

CREATE INDEX IF NOT EXISTS idx_local_manifest_rows_prune_pending
    ON local_manifest_export_rows(export_id, source_file_id)
    WHERE eligible AND pruned_at IS NULL;

CREATE TABLE IF NOT EXISTS local_manifest_segments (
    export_id          BIGINT NOT NULL
        REFERENCES local_manifest_exports(export_id) ON DELETE RESTRICT,
    manifest_relpath   TEXT NOT NULL,
    row_count          BIGINT NOT NULL CHECK (row_count >= 0),
    original_bytes     BIGINT NOT NULL CHECK (original_bytes >= 0),
    covered_rows       BIGINT NOT NULL CHECK (covered_rows >= 0),
    covered_bytes      BIGINT NOT NULL CHECK (covered_bytes >= 0),
    uncovered_rows     BIGINT NOT NULL CHECK (uncovered_rows >= 0),
    uncovered_bytes    BIGINT NOT NULL CHECK (uncovered_bytes >= 0),
    compressed_bytes   BIGINT NOT NULL CHECK (compressed_bytes >= 0),
    sha256_hex         TEXT NOT NULL CHECK (length(sha256_hex) = 64),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (export_id, manifest_relpath)
);

-- These are the permanent PostgreSQL folder totals for rows removed from
-- files_index. They deliberately contain no file names or per-file paths.
CREATE TABLE IF NOT EXISTS local_manifest_folder_aggregates (
    aggregate_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    export_id             BIGINT NOT NULL
        REFERENCES local_manifest_exports(export_id) ON DELETE RESTRICT,
    source_host           TEXT NOT NULL,
    tape_label            TEXT NOT NULL REFERENCES tapes(volume_label)
        ON UPDATE CASCADE ON DELETE CASCADE,
    original_dir_path     TEXT NOT NULL,
    direct_file_count     BIGINT NOT NULL CHECK (direct_file_count >= 0),
    direct_bytes          BIGINT NOT NULL CHECK (direct_bytes >= 0),
    direct_uncovered_file_count BIGINT NOT NULL
        CHECK (direct_uncovered_file_count >= 0),
    direct_uncovered_bytes BIGINT NOT NULL CHECK (direct_uncovered_bytes >= 0),
    recursive_file_count  BIGINT NOT NULL CHECK (recursive_file_count >= 0),
    recursive_bytes       BIGINT NOT NULL CHECK (recursive_bytes >= 0),
    recursive_uncovered_file_count BIGINT NOT NULL
        CHECK (recursive_uncovered_file_count >= 0),
    recursive_uncovered_bytes BIGINT NOT NULL
        CHECK (recursive_uncovered_bytes >= 0),
    backup_date           TIMESTAMPTZ NOT NULL,
    UNIQUE (export_id, source_host, tape_label, original_dir_path)
);

CREATE INDEX IF NOT EXISTS idx_local_manifest_folder_path
    ON local_manifest_folder_aggregates(
        source_host, tape_label, original_dir_path);

-- Same aggregate facts keyed to the catalog tree for fast inspector totals.
CREATE TABLE IF NOT EXISTS local_manifest_catalog_aggregates (
    export_id             BIGINT NOT NULL
        REFERENCES local_manifest_exports(export_id) ON DELETE RESTRICT,
    directory_id          BIGINT NOT NULL
        REFERENCES catalog_directories(directory_id) ON DELETE CASCADE,
    direct_file_count     BIGINT NOT NULL CHECK (direct_file_count >= 0),
    direct_bytes          BIGINT NOT NULL CHECK (direct_bytes >= 0),
    recursive_file_count  BIGINT NOT NULL CHECK (recursive_file_count >= 0),
    recursive_bytes       BIGINT NOT NULL CHECK (recursive_bytes >= 0),
    PRIMARY KEY (export_id, directory_id)
);

CREATE INDEX IF NOT EXISTS idx_local_manifest_catalog_directory
    ON local_manifest_catalog_aggregates(directory_id, export_id);

COMMIT;
