-- 013: generation-aware, crash-safe destructive tape reset.
--
-- A physical format reuses the LTFS volume label, but it does not make the
-- previous physical contents part of the new filesystem generation.  Keep the
-- stable tapes row, record each physical generation separately, and pin remote
-- sessions to the generation they were created against.

BEGIN;

ALTER TABLE tapes
    ADD COLUMN IF NOT EXISTS current_generation INTEGER NOT NULL DEFAULT 1;

ALTER TABLE remote_sessions
    ADD COLUMN IF NOT EXISTS tape_generation INTEGER;

UPDATE remote_sessions AS s
SET tape_generation = t.current_generation
FROM tapes AS t
WHERE t.volume_label = s.tape_label
  AND s.tape_generation IS NULL;

ALTER TABLE remote_sessions
    ALTER COLUMN tape_generation SET NOT NULL;

CREATE TABLE IF NOT EXISTS tape_reset_operations (
    operation_id          TEXT PRIMARY KEY,
    target_tape_id        BIGINT NOT NULL REFERENCES tapes(tape_id)
                              ON DELETE RESTRICT,
    target_label          TEXT NOT NULL,
    old_generation        INTEGER NOT NULL CHECK (old_generation >= 1),
    new_generation        INTEGER NOT NULL CHECK (new_generation >= 2),
    state                 TEXT NOT NULL,
    expected_drive        TEXT NOT NULL,
    expected_drive_serial TEXT NOT NULL,
    expected_ltfs_gen     INTEGER,
    expected_vcr          BIGINT,
    backup_path           TEXT NOT NULL,
    backup_sha256         TEXT NOT NULL CHECK (length(backup_sha256) = 64),
    restore_list_path     TEXT NOT NULL,
    restore_list_sha256   TEXT NOT NULL CHECK (length(restore_list_sha256) = 64),
    shadow_database       TEXT NOT NULL,
    impact_report_path    TEXT NOT NULL,
    impact_report_sha256  TEXT NOT NULL CHECK (length(impact_report_sha256) = 64),
    impact                JSONB NOT NULL,
    hardware_evidence     JSONB,
    cleanup_evidence      JSONB,
    error_message         TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    hardware_started_at   TIMESTAMPTZ,
    hardware_succeeded_at TIMESTAMPTZ,
    cleanup_succeeded_at  TIMESTAMPTZ,
    verified_at           TIMESTAMPTZ,
    CONSTRAINT tape_reset_generation_ck
        CHECK (new_generation = old_generation + 1),
    CONSTRAINT tape_reset_state_ck CHECK (state IN
        ('intent_recorded','hardware_started','hardware_succeeded',
         'cleanup_succeeded','verified','failed'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tape_reset_open_operation
    ON tape_reset_operations(target_tape_id)
    WHERE state IN ('intent_recorded','hardware_started','hardware_succeeded',
                    'cleanup_succeeded');

CREATE TABLE IF NOT EXISTS tape_generations (
    generation_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tape_id             BIGINT NOT NULL REFERENCES tapes(tape_id)
                            ON DELETE RESTRICT,
    volume_label        TEXT NOT NULL,
    generation          INTEGER NOT NULL CHECK (generation >= 1),
    state               TEXT NOT NULL CHECK (state IN ('active','retired')),
    formatted_at        TIMESTAMPTZ,
    retired_at          TIMESTAMPTZ,
    retired_reason      TEXT,
    reset_operation_id  TEXT REFERENCES tape_reset_operations(operation_id)
                            ON DELETE RESTRICT,
    UNIQUE (tape_id, generation)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tape_generations_one_active
    ON tape_generations(tape_id) WHERE state='active';

INSERT INTO tape_generations
    (tape_id, volume_label, generation, state, formatted_at)
SELECT tape_id, volume_label, current_generation, 'active', date_formatted
FROM tapes
ON CONFLICT (tape_id, generation) DO NOTHING;

-- A tape-row delete must never erase or rewrite archive history through a
-- cascading/set-null side effect.  Convert every live FK to tapes into a
-- restrictive relationship, including optional catalog schemas installed on
-- production but absent in smaller test databases.
DO $$
DECLARE
    r RECORD;
    definition TEXT;
BEGIN
    FOR r IN
        SELECT c.oid, c.conname, c.conrelid,
               c.conrelid::regclass AS child_table,
               pg_get_constraintdef(c.oid) AS definition
        FROM pg_constraint AS c
        WHERE c.contype='f'
          AND c.confrelid='tapes'::regclass
          AND c.confdeltype IN ('c','n')
    LOOP
        definition := regexp_replace(
            r.definition,
            ' ON DELETE (CASCADE|SET NULL)',
            ' ON DELETE RESTRICT');
        EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I',
                       r.child_table, r.conname);
        EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I %s',
                       r.child_table, r.conname, definition);
    END LOOP;
END $$;

COMMIT;
