-- 014_postgres_incremental_scan.sql  —  BASE (additive, idempotent)
--
-- Plan 1, Task 2.1.  Persists the minimum state an incremental directory
-- frontier needs, so a restart re-lists only the ONE directory that was
-- mid-listing instead of replaying every configured root from the beginning.
--
-- This file is deliberately the SAFE half of migration 014:
--   * every statement is additive and idempotent (CREATE ... IF NOT EXISTS,
--     ADD COLUMN IF NOT EXISTS);
--   * every new column on an existing table is NULLABLE, so rows written by
--     older code stay legal and old sessions stay readable;
--   * it creates NO unique constraint over legacy data and repairs nothing.
--
-- The legacy membership audit and the final unique constraints live in
-- 014_postgres_incremental_scan_finalize.sql, as a SEPARATE explicit
-- operation, because they can FAIL on real data (duplicate plan ordinals) and
-- must never auto-resequence an ambiguous legacy plan.
--
-- Migration numbering note: 010 is the local-manifest-archive export and is NOT
-- reused here.  Nothing below assumes the OPTIONAL migrations 007 (directory
-- catalog) or 012 (sealed tape write batches) are installed.

-- ===========================================================================
-- Scopes: the configured source roots, as PERSISTED ORDER
-- ===========================================================================
-- remote_sessions.remote_path stores the selected roots newline-concatenated
-- into one text field, which cannot express order, containment or per-root
-- coverage.  A resumed scan must follow the order the SESSION recorded, not
-- whatever order config.ini happens to list today.
CREATE TABLE IF NOT EXISTS remote_scan_scopes (
    scan_scope_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        BIGINT NOT NULL REFERENCES remote_sessions(session_id)
                          ON DELETE CASCADE,
    scope_ordinal     INTEGER NOT NULL CHECK (scope_ordinal >= 0),
    -- 'file' is a single explicitly-selected file, not a tree.
    scope_kind        TEXT NOT NULL
                          CHECK (scope_kind IN ('directory','file')),
    source_root       TEXT NOT NULL,
    coverage_state    TEXT NOT NULL DEFAULT 'provisional'
                          CHECK (coverage_state IN
                                 ('provisional','final','error','invalidated')),
    -- Deliberately SEPARATE from coverage: "the tree was explored" and "every
    -- discovered entry was assigned to a plan" are different facts.
    planning_complete BOOLEAN NOT NULL DEFAULT FALSE,
    -- Lightweight source-mutation token re-read before global finality.
    observation_final TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (session_id, scope_ordinal),
    UNIQUE (session_id, source_root)
);

-- ===========================================================================
-- Directories: the frontier itself
-- ===========================================================================
-- THREE independent state columns, on purpose:
--   listing_state           this directory's OWN immediate listing
--   subtree_coverage_state  every descendant listing is terminal (traversal
--                           only — segment allocation is irrelevant to it)
--   planning_state          how much of what was found is assigned to chunks
-- Collapsing them is exactly how a partially-explored tree gets reported as
-- covered.
CREATE TABLE IF NOT EXISTS remote_scan_directories (
    scan_directory_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_scope_id          BIGINT NOT NULL
                               REFERENCES remote_scan_scopes(scan_scope_id)
                               ON DELETE CASCADE,
    canonical_path         TEXT NOT NULL,
    parent_path            TEXT,
    parent_directory_id    BIGINT
                               REFERENCES remote_scan_directories(scan_directory_id)
                               ON DELETE CASCADE,
    -- Stable within a scope, so ordinals are reproducible regardless of which
    -- worker listed which directory or in what wall-clock order.
    traversal_ordinal      BIGINT NOT NULL,
    listing_state          TEXT NOT NULL DEFAULT 'pending'
                               CHECK (listing_state IN
                                      ('pending','scanning','partial',
                                       'complete','error','invalidated')),
    subtree_coverage_state TEXT NOT NULL DEFAULT 'provisional'
                               CHECK (subtree_coverage_state IN
                                      ('provisional','final','error',
                                       'invalidated')),
    planning_state         TEXT NOT NULL DEFAULT 'unplanned'
                               CHECK (planning_state IN
                                      ('unplanned','partially_allocated',
                                       'fully_allocated','blocked')),
    last_committed_segment_id BIGINT,
    -- Source-mutation observations: before listing, after listing, and the
    -- final sweep.  A changed token invalidates this directory AND its
    -- ancestors.  Stable path/size/structure tokens still cannot detect a
    -- same-size content replacement; that residual risk is documented, not
    -- hidden.
    observation_before     TEXT,
    observation_after      TEXT,
    observation_final      TEXT,
    direct_file_count      BIGINT NOT NULL DEFAULT 0
                               CHECK (direct_file_count >= 0),
    direct_byte_count      BIGINT NOT NULL DEFAULT 0
                               CHECK (direct_byte_count >= 0),
    child_directory_count  INTEGER NOT NULL DEFAULT 0
                               CHECK (child_directory_count >= 0),
    error_count            INTEGER NOT NULL DEFAULT 0
                               CHECK (error_count >= 0),
    owner_token            TEXT,
    attempt_id             TEXT,
    lease_expires_at       TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (scan_scope_id, canonical_path),
    UNIQUE (scan_scope_id, traversal_ordinal)
);

CREATE INDEX IF NOT EXISTS ix_remote_scan_directories_claimable
    ON remote_scan_directories (scan_scope_id, traversal_ordinal)
    WHERE listing_state IN ('pending','partial');

-- ===========================================================================
-- Segments: ready ranges of scanned entries, addressed by stable ordinals
-- ===========================================================================
-- The per-file detail lives in a local JSONL.zst artifact, NOT in PostgreSQL:
-- a successful scan must not cost one catalog row per file.  Only the range,
-- the aggregate counts and a root-relative locator are persisted.
CREATE TABLE IF NOT EXISTS remote_scan_segments (
    scan_segment_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_directory_id       BIGINT NOT NULL
                                REFERENCES remote_scan_directories(scan_directory_id)
                                ON DELETE CASCADE,
    first_scan_ordinal      BIGINT NOT NULL CHECK (first_scan_ordinal >= 0),
    last_scan_ordinal       BIGINT NOT NULL CHECK (last_scan_ordinal >= 0),
    -- Advanced transactionally under this row's lock as chunks consume the
    -- segment.  Gaps and overlaps are rejected by the consumer, not repaired.
    next_unconsumed_ordinal BIGINT,
    -- ROOT-RELATIVE, resolved against ConfigManager.local_manifest_archive_root
    -- at read time, so a metadata backup can be relocated without rewriting
    -- database rows.  A '.part' path is never a ready locator: the artifact is
    -- published atomically first.
    locator                 TEXT NOT NULL
                                CHECK (locator NOT LIKE '%.part'),
    artifact_version        TEXT NOT NULL DEFAULT 'scan-segment-v1',
    artifact_size_bytes     BIGINT CHECK (artifact_size_bytes >= 0),
    file_count              BIGINT NOT NULL DEFAULT 0
                                CHECK (file_count >= 0),
    byte_count              BIGINT NOT NULL DEFAULT 0
                                CHECK (byte_count >= 0),
    first_canonical_path    TEXT,
    last_canonical_path     TEXT,
    state                   TEXT NOT NULL DEFAULT 'writing'
                                CHECK (state IN ('writing','ready',
                                                 'partially_consumed',
                                                 'consumed','invalidated')),
    -- ONE-TIME legacy reconciliation (Task 2.4). A session migrated onto the
    -- frontier has pre-existing snapshot rows; each segment is compared against
    -- them exactly once and then marked, so normal frontier progress never
    -- queries the legacy membership set again.  'blocked' means the comparison
    -- found a same-path/different-size entry, which needs a human.
    legacy_import_state     TEXT NOT NULL DEFAULT 'not_imported'
                                CHECK (legacy_import_state IN
                                       ('not_imported','imported','blocked')),
    legacy_imported_at      TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (last_scan_ordinal >= first_scan_ordinal),
    UNIQUE (scan_directory_id, first_scan_ordinal)
);

CREATE INDEX IF NOT EXISTS ix_remote_scan_segments_consumable
    ON remote_scan_segments (scan_directory_id, first_scan_ordinal)
    WHERE state IN ('ready','partially_consumed');

-- ===========================================================================
-- Chunk <-> segment membership
-- ===========================================================================
-- One chunk may consume several segments, and one segment may split across
-- several chunks — without duplicate membership.  The unique range identity
-- below is what makes that provable rather than hoped for.
CREATE TABLE IF NOT EXISTS remote_chunk_scan_segments (
    chunk_segment_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id         BIGINT NOT NULL,
    chunk_index        INTEGER NOT NULL CHECK (chunk_index >= 0),
    scan_segment_id    BIGINT NOT NULL
                           REFERENCES remote_scan_segments(scan_segment_id)
                           ON DELETE RESTRICT,
    first_scan_ordinal BIGINT NOT NULL CHECK (first_scan_ordinal >= 0),
    last_scan_ordinal  BIGINT NOT NULL CHECK (last_scan_ordinal >= 0),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (last_scan_ordinal >= first_scan_ordinal),
    FOREIGN KEY (session_id, chunk_index)
        REFERENCES remote_chunks(session_id, chunk_index) ON DELETE CASCADE,
    UNIQUE (scan_segment_id, first_scan_ordinal, last_scan_ordinal)
);

CREATE INDEX IF NOT EXISTS ix_remote_chunk_scan_segments_chunk
    ON remote_chunk_scan_segments (session_id, chunk_index);

-- ===========================================================================
-- Exceptional entries only
-- ===========================================================================
-- Compact records for entries and directories that could NOT be covered.
-- There is deliberately no success row per file: a scan of 82 million files
-- must not write 82 million rows to say so.
CREATE TABLE IF NOT EXISTS remote_scan_errors (
    scan_error_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_scope_id     BIGINT REFERENCES remote_scan_scopes(scan_scope_id)
                          ON DELETE CASCADE,
    scan_directory_id BIGINT REFERENCES remote_scan_directories(scan_directory_id)
                          ON DELETE CASCADE,
    category          TEXT NOT NULL,
    -- NULL when the path is not representable (invalid UTF-8, truncated
    -- record).  The category and the directory still record that something
    -- was missed, which is the fact coverage depends on.
    path              TEXT,
    message           TEXT,
    disposition       TEXT NOT NULL DEFAULT 'unresolved'
                          CHECK (disposition IN ('unresolved','skipped',
                                                 'retried','accepted')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_remote_scan_errors_directory
    ON remote_scan_errors (scan_directory_id);

-- ===========================================================================
-- Worker attempts: durable evidence, because an in-memory registry is not
-- ===========================================================================
-- src.runtime's process registry is CURRENT-PROCESS cleanup only; it proves
-- nothing after a crash.  Reconciliation needs a local PID *plus* its process
-- creation identity (PIDs are reused), and a token the REMOTE process group
-- was tagged with, so an orphan can be identified rather than guessed at.
CREATE TABLE IF NOT EXISTS remote_worker_attempts (
    attempt_id              TEXT PRIMARY KEY,
    owner_token             TEXT NOT NULL,
    session_id              BIGINT REFERENCES remote_sessions(session_id)
                                ON DELETE CASCADE,
    chunk_index             INTEGER CHECK (chunk_index >= 0),
    scan_directory_id       BIGINT
                                REFERENCES remote_scan_directories(scan_directory_id)
                                ON DELETE SET NULL,
    attempt_kind            TEXT NOT NULL
                                CHECK (attempt_kind IN ('scan','fetch','pack',
                                                        'write')),
    local_pid               INTEGER,
    local_process_started_at TIMESTAMPTZ,
    remote_command_token    TEXT,
    remote_process_group    TEXT,
    lease_expires_at        TIMESTAMPTZ,
    heartbeat_at            TIMESTAMPTZ,
    terminal_state          TEXT
                                CHECK (terminal_state IS NULL OR
                                       terminal_state IN ('completed','failed',
                                                          'abandoned',
                                                          'orphan_terminated',
                                                          'indeterminate')),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_remote_worker_attempts_live
    ON remote_worker_attempts (session_id, attempt_kind)
    WHERE terminal_state IS NULL;

-- ===========================================================================
-- Bootstrap runs: the ONE-TIME migration of a legacy session onto the frontier
-- ===========================================================================
-- Durable because it is resumable: a bootstrap traverses a real source tree and
-- can be interrupted. Without a run record, a second attempt could not tell
-- what the first had already established, and "start again from nothing" is
-- exactly the replay the frontier exists to remove.
--
-- The partial unique index enforces the "one-time" part: a session may have at
-- most one bootstrap that is not finished.
CREATE TABLE IF NOT EXISTS remote_frontier_bootstraps (
    bootstrap_id      TEXT PRIMARY KEY,
    session_id        BIGINT NOT NULL REFERENCES remote_sessions(session_id)
                          ON DELETE CASCADE,
    source_host       TEXT,
    state             TEXT NOT NULL DEFAULT 'planned'
                          CHECK (state IN ('planned','running','completed',
                                           'failed','abandoned')),
    scopes_created    INTEGER NOT NULL DEFAULT 0,
    directories_listed INTEGER NOT NULL DEFAULT 0,
    segments_published INTEGER NOT NULL DEFAULT 0,
    segments_imported INTEGER NOT NULL DEFAULT 0,
    entries_covered   BIGINT NOT NULL DEFAULT 0,
    entries_new       BIGINT NOT NULL DEFAULT 0,
    entries_changed   BIGINT NOT NULL DEFAULT 0,
    coverage_final    BOOLEAN NOT NULL DEFAULT FALSE,
    detail            TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_remote_frontier_bootstrap_open
    ON remote_frontier_bootstraps (session_id)
    WHERE state IN ('planned','running');

-- ===========================================================================
-- remote_chunks: claim + membership + expectation columns (ALL NULLABLE)
-- ===========================================================================
-- Nullable for legacy: existing chunks keep NULL and stay exactly as valid as
-- they were.  New chunks are required to be 'building' or 'sealed', but that
-- requirement is enforced by the application and by the FINALIZE step, never
-- by a retroactive NOT NULL that would rewrite history.
ALTER TABLE remote_chunks
    ADD COLUMN IF NOT EXISTS owner_token         TEXT,
    ADD COLUMN IF NOT EXISTS lease_expires_at    TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS attempt_id          TEXT,
    ADD COLUMN IF NOT EXISTS membership_state    TEXT,
    ADD COLUMN IF NOT EXISTS expected_file_count BIGINT,
    -- LOGICAL PLANNED SOURCE BYTES.  Deliberately distinct from Plan 2's
    -- actual staged bytes: they differ by compression and cluster rounding,
    -- and conflating them would make a capacity check quietly wrong.
    ADD COLUMN IF NOT EXISTS expected_bytes      BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'remote_chunks_membership_state_check'
          AND conrelid = 'remote_chunks'::regclass
    ) THEN
        ALTER TABLE remote_chunks
            ADD CONSTRAINT remote_chunks_membership_state_check
            CHECK (membership_state IS NULL
                   OR membership_state IN ('building','sealed'))
            NOT VALID;
    END IF;
END $$;

ALTER TABLE remote_chunks
    VALIDATE CONSTRAINT remote_chunks_membership_state_check;

-- ===========================================================================
-- remote_file_state: richer SOURCE outcomes
-- ===========================================================================
-- 'source_missing' alone cannot distinguish "the file is gone" from "we were
-- not allowed to read it", "the directory was unreadable", "it changed size
-- after planning" and "we do not know".  Those need different operator
-- responses, so they get different values instead of one bucket.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'remote_file_state_status_check'
          AND conrelid = 'remote_file_state'::regclass
    ) THEN
        ALTER TABLE remote_file_state
            DROP CONSTRAINT remote_file_state_status_check;
    END IF;

    ALTER TABLE remote_file_state
        ADD CONSTRAINT remote_file_state_status_check
        CHECK (status IS NULL OR status IN
               ('pending','fetching','fetched','fetch_failed','source_missing',
                'source_permission_denied','source_unreadable','source_changed',
                'unresolved'))
        NOT VALID;
END $$;

ALTER TABLE remote_file_state
    VALIDATE CONSTRAINT remote_file_state_status_check;

-- ===========================================================================
-- Marker
-- ===========================================================================
-- The presence of every table above is what
-- PgConnectionCore.incremental_scan_schema_installed() checks.  Being
-- "installed" is NOT the same as being "finalized"; the frontier requires
-- both, and the FINALIZE file is what grants the second.
COMMENT ON TABLE remote_scan_scopes IS
    'Plan 1 migration 014 (base): persisted, ordered source roots per session.';
