"""Maintenance-only hot files_index -> cold small-file catalog migration."""
import json
import os
import time
from contextlib import contextmanager
from datetime import datetime, timezone
from typing import Any, TYPE_CHECKING, cast

if TYPE_CHECKING:
    import psycopg
    from psycopg.rows import dict_row
else:
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError:  # pragma: no cover - runtime dependency path
        psycopg = None
        dict_row = None

from .catalog_query import escape_like_literal
from .pg_bulk import build_conninfo, copy_rows, require_psycopg


SOURCE_TABLE = "files_index"
COLD_PAYLOAD_TABLE = "small_file_manifest_cold"
COLD_PAYLOAD_UNIQUE_INDEX = "uq_cold_manifest_source"


def _now():
    return datetime.now(timezone.utc)


def _connect(conninfo, *, autocommit=False):
    require_psycopg()
    return cast(Any, psycopg.connect(
        conninfo, autocommit=autocommit,
        row_factory=cast(Any, dict_row)))


def cold_conninfo(cfg):
    return build_conninfo(
        host=cfg.cold_pg_host,
        port=cfg.cold_pg_port,
        dbname=cfg.cold_pg_dbname,
        user=cfg.cold_pg_user,
        password=cfg.cold_pg_password,
        sslmode=cfg.cold_pg_sslmode,
    )


class ColdBackupConfig:
    """Config adapter for pg_backup helpers against the cold DB."""

    pg_docker_container = "lto_cold_manifest_pg"

    def __init__(self, cfg):
        self._cfg = cfg

    @property
    def pg_host(self):
        return self._cfg.cold_pg_host

    @property
    def pg_port(self):
        return self._cfg.cold_pg_port

    @property
    def pg_dbname(self):
        return self._cfg.cold_pg_dbname

    @property
    def pg_user(self):
        return self._cfg.cold_pg_user

    @property
    def pg_password(self):
        return self._cfg.cold_pg_password

    @property
    def pg_sslmode(self):
        return self._cfg.cold_pg_sslmode

    @property
    def db_display_ref(self):
        return self._cfg.cold_db_display_ref


def threshold_bytes(cfg):
    return int(float(cfg.cold_small_file_threshold_mb) * 1024 * 1024)


def _table_exists(conn, name):
    return conn.execute(
        """SELECT 1
           FROM information_schema.tables
           WHERE table_schema='public' AND table_name=%s""",
        (name,),
    ).fetchone() is not None


def _valid_identifier(value):
    return bool(value) and str(value).replace("_", "").isalnum()


def detect_source_id_column(conn):
    rows = conn.execute(
        """SELECT a.attname AS column_name
           FROM pg_index i
           JOIN pg_class t ON t.oid=i.indrelid
           JOIN pg_namespace n ON n.oid=t.relnamespace
           JOIN pg_attribute a
             ON a.attrelid=t.oid AND a.attnum = ANY(i.indkey)
           WHERE n.nspname='public'
             AND t.relname=%s
             AND i.indisprimary
           ORDER BY a.attnum""",
        (SOURCE_TABLE,),
    ).fetchall()
    if len(rows) != 1:
        return None
    column = rows[0]["column_name"]
    return column if _valid_identifier(column) else None


def ensure_hot_schema(conn):
    conn.execute("""
        CREATE TABLE IF NOT EXISTS small_file_cold_migrations (
            migration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            threshold_bytes BIGINT NOT NULL,
            hot_db_name TEXT NOT NULL,
            cold_db_name TEXT NOT NULL,
            hot_backup_path TEXT,
            cold_backup_path TEXT,
            cold_backup_verified BOOLEAN NOT NULL DEFAULT FALSE,
            source_hot_table TEXT NOT NULL DEFAULT 'files_index',
            source_hot_id_column TEXT,
            status TEXT NOT NULL,
            eligible_rows BIGINT NOT NULL DEFAULT 0,
            eligible_bytes BIGINT NOT NULL DEFAULT 0,
            copied_rows BIGINT NOT NULL DEFAULT 0,
            copied_bytes BIGINT NOT NULL DEFAULT 0,
            validated_rows BIGINT,
            validation_passed BOOLEAN NOT NULL DEFAULT FALSE,
            validation_report JSONB,
            removal_report JSONB,
            started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            validated_at TIMESTAMPTZ,
            finished_at TIMESTAMPTZ,
            error_message TEXT
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS small_file_cold_migration_sources (
            migration_id BIGINT NOT NULL
                REFERENCES small_file_cold_migrations(migration_id)
                ON DELETE CASCADE,
            source_hot_table TEXT NOT NULL,
            source_hot_row_id BIGINT NOT NULL,
            tape_label TEXT NOT NULL,
            file_size_bytes BIGINT NOT NULL CHECK (file_size_bytes >= 0),
            archive_run_id BIGINT,
            bundle_id BIGINT,
            covered_by_hot_accounting BOOLEAN NOT NULL DEFAULT FALSE,
            PRIMARY KEY (migration_id, source_hot_table, source_hot_row_id)
        )
    """)
    conn.execute("""
        CREATE INDEX IF NOT EXISTS idx_small_file_cold_sources_tape
        ON small_file_cold_migration_sources(migration_id, tape_label)
    """)
    conn.execute("""
        CREATE INDEX IF NOT EXISTS idx_small_file_cold_sources_covered
        ON small_file_cold_migration_sources(migration_id, covered_by_hot_accounting)
    """)


def ensure_cold_schema(conn):
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS {COLD_PAYLOAD_TABLE} (
            migration_id BIGINT,
            source_hot_table TEXT,
            source_hot_row_id BIGINT,
            source_host TEXT,
            tape_label TEXT,
            archive_run_id BIGINT NULL,
            local_session_id BIGINT NULL,
            remote_session_id BIGINT NULL,
            chunk_index INTEGER NULL,
            bundle_id BIGINT NULL,
            stored_bundle_path TEXT NULL,
            original_root_dir TEXT NULL,
            relative_path TEXT,
            file_name TEXT,
            size_bytes BIGINT,
            mtime TIMESTAMPTZ NULL,
            source_kind TEXT,
            loaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS small_file_cold_loads (
            load_id BIGSERIAL PRIMARY KEY,
            migration_id BIGINT,
            expected_rows BIGINT,
            loaded_rows BIGINT NOT NULL DEFAULT 0,
            status TEXT NOT NULL,
            started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            finished_at TIMESTAMPTZ NULL,
            error_message TEXT NULL
        )
    """)
    _ensure_cold_payload_unique_index(conn)


def _ensure_cold_payload_unique_index(conn):
    """Attach the payload identity index, deduplicating legacy rows first.

    The payload table historically had no constraints, so a partially failed
    copy that was manually retried could have duplicated
    (migration_id, source_hot_table, source_hot_row_id). The one-time dedupe
    keeps the lowest ctid so the index can attach on an existing database.
    """
    exists = conn.execute(
        """SELECT 1 FROM pg_indexes
           WHERE schemaname='public' AND tablename=%s AND indexname=%s""",
        (COLD_PAYLOAD_TABLE, COLD_PAYLOAD_UNIQUE_INDEX),
    ).fetchone() is not None
    if exists:
        return
    conn.execute(f"""
        DELETE FROM {COLD_PAYLOAD_TABLE} a
        USING {COLD_PAYLOAD_TABLE} b
        WHERE a.ctid > b.ctid
          AND a.migration_id IS NOT DISTINCT FROM b.migration_id
          AND a.source_hot_table IS NOT DISTINCT FROM b.source_hot_table
          AND a.source_hot_row_id IS NOT DISTINCT FROM b.source_hot_row_id
    """)
    conn.execute(f"""
        CREATE UNIQUE INDEX IF NOT EXISTS {COLD_PAYLOAD_UNIQUE_INDEX}
        ON {COLD_PAYLOAD_TABLE}
        (migration_id, source_hot_table, source_hot_row_id)
    """)


def purge_failed_migration_payload(hot, cold):
    """Remove cold payload rows left behind by FAILED hot migrations.

    A mid-copy abort commits per-batch payload rows under a migration whose
    hot status ends up 'failed'; those rows are incomplete copies (the hot
    rows are never deleted for a failed migration) and previously required
    manual cleanup. Returns the number of cold rows purged."""
    failed_ids = [
        row["migration_id"] for row in hot.execute(
            """SELECT migration_id FROM small_file_cold_migrations
               WHERE status='failed'"""
        ).fetchall()
    ]
    if not failed_ids:
        return 0
    purged = cold.execute(
        f"DELETE FROM {COLD_PAYLOAD_TABLE} WHERE migration_id = ANY(%s)",
        (failed_ids,),
    ).rowcount
    cold.execute(
        """UPDATE small_file_cold_loads
           SET status='purged', finished_at=now()
           WHERE migration_id = ANY(%s) AND status='failed'""",
        (failed_ids,),
    )
    return purged


def cold_payload_index_report(conn):
    rows = conn.execute(
        """SELECT c.conname, c.contype
           FROM pg_constraint c
           JOIN pg_class t ON t.oid=c.conrelid
           WHERE t.relname=%s""",
        (COLD_PAYLOAD_TABLE,),
    ).fetchall()
    indexes = conn.execute(
        """SELECT indexname
           FROM pg_indexes
           WHERE schemaname='public' AND tablename=%s""",
        (COLD_PAYLOAD_TABLE,),
    ).fetchall()
    logged = conn.execute(
        """SELECT relpersistence
           FROM pg_class
           WHERE relname=%s""",
        (COLD_PAYLOAD_TABLE,),
    ).fetchone()
    return {
        "constraints": [dict(row) for row in rows],
        "indexes": [row["indexname"] for row in indexes],
        "logged": bool(logged and logged["relpersistence"] == "p"),
    }


def _coverage_expr(directory_catalog_available):
    if not directory_catalog_available:
        return "FALSE"
    return """(
        f.bundle_id IS NOT NULL
        AND b.tape_path IS NOT NULL
        AND EXISTS (
            SELECT 1
            FROM directory_archive_bundles db
            WHERE db.tape_label=f.tape_label
              AND db.stored_bundle_path=b.tape_path
        )
    )"""


def _migration_row(conn, migration_id):
    return conn.execute(
        """SELECT * FROM small_file_cold_migrations
           WHERE migration_id=%s""",
        (migration_id,),
    ).fetchone()


def dry_run_migration(hot_conninfo, cfg):
    threshold = threshold_bytes(cfg)
    with _connect(hot_conninfo, autocommit=True) as hot:
        ensure_hot_schema(hot)
        row = hot.execute(
            """SELECT COUNT(*) AS eligible_rows,
                      COALESCE(SUM(file_size_bytes), 0) AS eligible_bytes
               FROM files_index
               WHERE file_size_bytes < %s""",
            (threshold,),
        ).fetchone()
        return {
            "mode": "dry-run",
            "threshold_bytes": threshold,
            "eligible_rows": int(row["eligible_rows"] or 0),
            "eligible_bytes": int(row["eligible_bytes"] or 0),
            "copied_rows": 0,
        }


def _resource_check(governor, label):
    if governor is None:
        return
    if not governor.can_start_cold_migration():
        raise RuntimeError(
            f"[COLD] Resource Governor refused {label}; archive/resource "
            "activity is active or local resources are unsafe.")


def execute_migration(hot_conninfo, cold_conninfo_value, cfg, *,
                      hot_backup_path, governor=None):
    if not hot_backup_path:
        raise RuntimeError(
            "[COLD] --hot-backup-path is required for migration execute.")
    _resource_check(governor, "cold migration start")
    threshold = threshold_bytes(cfg)
    batch_rows = int(cfg.cold_batch_rows)
    fetch_rows = int(cfg.cold_fetch_rows)
    sleep_s = int(cfg.cold_sleep_between_batches_ms) / 1000.0
    cold_dbname = cfg.cold_pg_dbname

    with _connect(hot_conninfo) as hot, _connect(cold_conninfo_value) as cold:
        ensure_hot_schema(hot)
        ensure_cold_schema(cold)
        hot.commit()
        cold.commit()

        # Reclaim orphans from earlier aborted copies before starting a new
        # one, so failed-migration payload rows never accumulate in the cold
        # DB awaiting manual cleanup.
        purged = purge_failed_migration_payload(hot, cold)
        cold.commit()
        hot.commit()  # close the read-only implicit txn the purge opened
        if purged:
            print(f"[COLD] Purged {purged:,} orphaned payload row(s) from "
                  "previously failed migration(s).")

        source_id_column = detect_source_id_column(hot)
        if not source_id_column:
            raise RuntimeError(
                "[COLD] files_index has no single-column primary key; safe "
                "hot-row removal is disabled.")

        directory_catalog_available = _table_exists(
            hot, "directory_archive_bundles")
        coverage = _coverage_expr(directory_catalog_available)

        # Close the implicit transaction the reads above opened. Without this,
        # psycopg turns the snapshot block below into a SAVEPOINT inside that
        # implicit transaction, so the "committed" snapshot was never durable:
        # the except handler's hot.rollback() wiped the whole snapshot and the
        # follow-up status='failed' UPDATE matched nothing — leaving cold
        # orphans with no failed hot record for the purge to find.
        hot.commit()

        with hot.transaction():
            migration_id = hot.execute(
                """INSERT INTO small_file_cold_migrations
                   (threshold_bytes, hot_db_name, cold_db_name,
                    hot_backup_path, source_hot_table, source_hot_id_column,
                    status)
                   VALUES (%s, current_database(), %s, %s, 'files_index',
                           %s, 'snapshotting')
                   RETURNING migration_id""",
                (threshold, cold_dbname, str(hot_backup_path),
                 source_id_column),
            ).fetchone()["migration_id"]
            hot.execute(
                f"""INSERT INTO small_file_cold_migration_sources
                    (migration_id, source_hot_table, source_hot_row_id,
                     tape_label, file_size_bytes, archive_run_id, bundle_id,
                     covered_by_hot_accounting)
                    SELECT %s, 'files_index', f.{source_id_column},
                           f.tape_label, f.file_size_bytes, f.archive_run_id,
                           f.bundle_id, {coverage}
                    FROM files_index f
                    LEFT JOIN archive_bundles b ON b.bundle_id=f.bundle_id
                    WHERE f.file_size_bytes < %s""",
                (migration_id, threshold),
            )
            counts = hot.execute(
                """SELECT COUNT(*) AS rows,
                          COALESCE(SUM(file_size_bytes), 0) AS bytes
                   FROM small_file_cold_migration_sources
                   WHERE migration_id=%s""",
                (migration_id,),
            ).fetchone()
            hot.execute(
                """UPDATE small_file_cold_migrations
                   SET status='copying', eligible_rows=%s, eligible_bytes=%s
                   WHERE migration_id=%s""",
                (counts["rows"], counts["bytes"], migration_id),
            )

        copied_rows = 0
        copied_bytes = 0
        load_id = cold.execute(
            """INSERT INTO small_file_cold_loads
               (migration_id, expected_rows, status)
               VALUES (%s, %s, 'copying')
               RETURNING load_id""",
            (migration_id, counts["rows"]),
        ).fetchone()["load_id"]
        cold.commit()

        columns = (
            "migration_id", "source_hot_table", "source_hot_row_id",
            "source_host", "tape_label", "archive_run_id",
            "local_session_id", "remote_session_id", "chunk_index",
            "bundle_id", "stored_bundle_path", "original_root_dir",
            "relative_path", "file_name", "size_bytes", "mtime",
            "source_kind",
        )
        col_sql = ", ".join(columns)

        def _load_cold_batch(batch):
            """COPY a batch through a temp table and upsert idempotently.

            ON CONFLICT DO NOTHING against the payload identity index makes a
            retried batch (ambiguous commit, operator re-run) converge instead
            of duplicating rows. Returns the number of rows actually inserted.
            """
            with cold.transaction():
                cold.execute(
                    "CREATE TEMP TABLE _cold_stage ON COMMIT DROP AS "
                    f"SELECT {col_sql} FROM {COLD_PAYLOAD_TABLE} WITH NO DATA"
                )
                with cold.cursor() as copy_cur:
                    copy_rows(copy_cur, "_cold_stage", columns, batch)
                return cold.execute(
                    f"""INSERT INTO {COLD_PAYLOAD_TABLE} ({col_sql})
                        SELECT {col_sql} FROM _cold_stage
                        ON CONFLICT (migration_id, source_hot_table,
                                     source_hot_row_id) DO NOTHING"""
                ).rowcount

        try:
            with hot.cursor(name=f"cold_migration_{migration_id}") as cur:
                cur.itersize = fetch_rows
                cur.execute(
                    f"""SELECT s.migration_id, s.source_hot_table,
                               s.source_hot_row_id, f.source_host,
                               f.tape_label, f.archive_run_id,
                               f.local_session_id, f.remote_session_id,
                               COALESCE(f.local_chunk_index,
                                        f.remote_chunk_index) AS chunk_index,
                               f.bundle_id, b.tape_path AS stored_bundle_path,
                               NULL::text AS original_root_dir,
                               f.stored_path AS relative_path,
                               f.catalog_name AS file_name,
                               f.file_size_bytes AS size_bytes,
                               f.catalog_backup_date AS mtime,
                               CASE WHEN f.is_packed THEN 'packed'
                                    ELSE 'legacy_hot_small' END AS source_kind
                        FROM small_file_cold_migration_sources s
                        JOIN files_index f
                          ON f.{source_id_column}=s.source_hot_row_id
                        LEFT JOIN archive_bundles b ON b.bundle_id=f.bundle_id
                        WHERE s.migration_id=%s
                        ORDER BY s.source_hot_row_id""",
                    (migration_id,),
                )
                while True:
                    _resource_check(governor, "cold migration copy batch")
                    rows = cur.fetchmany(fetch_rows)
                    if not rows:
                        break
                    batch = []
                    for row in rows:
                        batch.append([row[column] for column in columns])
                        copied_rows += 1
                        copied_bytes += int(row["size_bytes"] or 0)
                        if len(batch) >= batch_rows:
                            _load_cold_batch(batch)
                            batch = []
                            if sleep_s:
                                time.sleep(sleep_s)
                            _resource_check(
                                governor, "cold migration copy buffer")
                    if batch:
                        _load_cold_batch(batch)
                    if sleep_s:
                        time.sleep(sleep_s)

            cold.execute(
                """UPDATE small_file_cold_loads
                   SET status='copied', loaded_rows=%s, finished_at=now()
                   WHERE load_id=%s""",
                (copied_rows, load_id),
            )
            cold.commit()
            with hot.transaction():
                hot.execute(
                    """UPDATE small_file_cold_migrations
                       SET status='copied', copied_rows=%s, copied_bytes=%s,
                           finished_at=now()
                       WHERE migration_id=%s""",
                    (copied_rows, copied_bytes, migration_id),
                )
        except Exception as exc:
            cold.rollback()
            hot.rollback()
            try:
                cold.execute(
                    """UPDATE small_file_cold_loads
                       SET status='failed', loaded_rows=%s,
                           finished_at=now(), error_message=%s
                       WHERE load_id=%s""",
                    (copied_rows, str(exc), load_id),
                )
                cold.commit()
                hot.execute(
                    """UPDATE small_file_cold_migrations
                       SET status='failed', copied_rows=%s, copied_bytes=%s,
                           finished_at=now(), error_message=%s
                       WHERE migration_id=%s""",
                    (copied_rows, copied_bytes, str(exc), migration_id),
                )
                hot.commit()
            finally:
                pass
            raise

    return {
        "mode": "execute",
        "migration_id": int(migration_id),
        "threshold_bytes": threshold,
        "hot_backup_path": str(hot_backup_path),
        "eligible_rows": int(counts["rows"] or 0),
        "eligible_bytes": int(counts["bytes"] or 0),
        "copied_rows": copied_rows,
        "copied_bytes": copied_bytes,
    }


def _aggregate_rows(conn, sql_text, params):
    return [dict(row) for row in conn.execute(sql_text, params).fetchall()]


def _keyed(rows, keys):
    result = {}
    for row in rows:
        key = tuple(row.get(item) for item in keys)
        result[key] = {
            "rows": int(row.get("rows") or 0),
            "bytes": int(row.get("bytes") or 0),
        }
    return result


def validate_migration(hot_conninfo, cold_conninfo_value, migration_id,
                       *, governor=None):
    _resource_check(governor, "cold migration validation")
    with _connect(hot_conninfo, autocommit=True) as hot, \
            _connect(cold_conninfo_value, autocommit=True) as cold:
        ensure_hot_schema(hot)
        ensure_cold_schema(cold)
        migration = _migration_row(hot, migration_id)
        if not migration:
            raise RuntimeError(f"[COLD] Migration not found: {migration_id}")

        hot_total = hot.execute(
            """SELECT COUNT(*) AS rows, COALESCE(SUM(file_size_bytes), 0) AS bytes
               FROM small_file_cold_migration_sources
               WHERE migration_id=%s""",
            (migration_id,),
        ).fetchone()
        cold_total = cold.execute(
            f"""SELECT COUNT(*) AS rows, COALESCE(SUM(size_bytes), 0) AS bytes
                FROM {COLD_PAYLOAD_TABLE}
                WHERE migration_id=%s""",
            (migration_id,),
        ).fetchone()
        hot_tape = _aggregate_rows(
            hot,
            """SELECT tape_label, COUNT(*) AS rows,
                      COALESCE(SUM(file_size_bytes), 0) AS bytes
               FROM small_file_cold_migration_sources
               WHERE migration_id=%s
               GROUP BY tape_label ORDER BY tape_label""",
            (migration_id,),
        )
        cold_tape = _aggregate_rows(
            cold,
            f"""SELECT tape_label, COUNT(*) AS rows,
                       COALESCE(SUM(size_bytes), 0) AS bytes
                FROM {COLD_PAYLOAD_TABLE}
                WHERE migration_id=%s
                GROUP BY tape_label ORDER BY tape_label""",
            (migration_id,),
        )
        hot_run = _aggregate_rows(
            hot,
            """SELECT archive_run_id, COUNT(*) AS rows,
                      COALESCE(SUM(file_size_bytes), 0) AS bytes
               FROM small_file_cold_migration_sources
               WHERE migration_id=%s
               GROUP BY archive_run_id ORDER BY archive_run_id""",
            (migration_id,),
        )
        cold_run = _aggregate_rows(
            cold,
            f"""SELECT archive_run_id, COUNT(*) AS rows,
                       COALESCE(SUM(size_bytes), 0) AS bytes
                FROM {COLD_PAYLOAD_TABLE}
                WHERE migration_id=%s
                GROUP BY archive_run_id ORDER BY archive_run_id""",
            (migration_id,),
        )
        cold_nulls = cold.execute(
            f"""SELECT
                    SUM(CASE WHEN source_hot_row_id IS NULL THEN 1 ELSE 0 END) AS source_hot_row_id,
                    SUM(CASE WHEN source_host IS NULL THEN 1 ELSE 0 END) AS source_host,
                    SUM(CASE WHEN tape_label IS NULL THEN 1 ELSE 0 END) AS tape_label,
                    SUM(CASE WHEN relative_path IS NULL THEN 1 ELSE 0 END) AS relative_path,
                    SUM(CASE WHEN file_name IS NULL THEN 1 ELSE 0 END) AS file_name,
                    SUM(CASE WHEN size_bytes IS NULL THEN 1 ELSE 0 END) AS size_bytes
                FROM {COLD_PAYLOAD_TABLE}
                WHERE migration_id=%s""",
            (migration_id,),
        ).fetchone()
        flags = hot.execute(
            """SELECT
                    SUM(CASE WHEN bundle_id IS NULL THEN 1 ELSE 0 END) AS missing_bundle_id,
                    SUM(CASE WHEN covered_by_hot_accounting THEN 1 ELSE 0 END) AS covered_rows,
                    SUM(CASE WHEN NOT covered_by_hot_accounting THEN 1 ELSE 0 END) AS uncovered_rows
               FROM small_file_cold_migration_sources
               WHERE migration_id=%s""",
            (migration_id,),
        ).fetchone()

        hot_total_obj = {
            "rows": int(hot_total["rows"] or 0),
            "bytes": int(hot_total["bytes"] or 0),
        }
        cold_total_obj = {
            "rows": int(cold_total["rows"] or 0),
            "bytes": int(cold_total["bytes"] or 0),
        }
        nulls = {key: int(cold_nulls[key] or 0) for key in cold_nulls.keys()}
        per_tape_match = _keyed(hot_tape, ("tape_label",)) == _keyed(
            cold_tape, ("tape_label",))
        per_run_match = _keyed(hot_run, ("archive_run_id",)) == _keyed(
            cold_run, ("archive_run_id",))
        passed = (
            hot_total_obj == cold_total_obj and
            per_tape_match and
            per_run_match and
            not any(nulls.values())
        )
        report = {
            "migration_id": int(migration_id),
            "passed": passed,
            "hot_snapshot": hot_total_obj,
            "cold_payload": cold_total_obj,
            "per_tape_match": per_tape_match,
            "per_archive_run_match": per_run_match,
            "missing_bundle_id": int(flags["missing_bundle_id"] or 0),
            "covered_rows": int(flags["covered_rows"] or 0),
            "uncovered_rows": int(flags["uncovered_rows"] or 0),
            "null_critical_fields": nulls,
        }
        hot.execute(
            """UPDATE small_file_cold_migrations
               SET status=%s, validated_rows=%s, validation_passed=%s,
                   validated_at=now(), validation_report=%s
               WHERE migration_id=%s""",
            ("validated" if passed else "validation_failed",
             cold_total_obj["rows"], passed, json.dumps(report), migration_id),
        )
        return report


def _used_space_by_tape(conn, tape_labels):
    labels = [label for label in tape_labels if label]
    if not labels:
        return {}
    if not _table_exists(conn, "directory_archive_bundles"):
        rows = conn.execute(
            """SELECT tape_label, COALESCE(SUM(file_size_bytes), 0) AS used
               FROM files_index
               WHERE tape_label = ANY(%s)
               GROUP BY tape_label""",
            (labels,),
        ).fetchall()
        return {row["tape_label"]: int(row["used"] or 0) for row in rows}
    rows = conn.execute(
        """WITH wanted AS (
               SELECT unnest(%s::text[]) AS tape_label
           ),
           bundle_paths AS (
               SELECT tape_label, stored_bundle_path
               FROM directory_archive_bundles
               WHERE tape_label = ANY(%s)
           ),
           legacy_file_bytes AS (
               SELECT w.tape_label,
                      COALESCE(SUM(f.file_size_bytes), 0) AS n
               FROM wanted w
               LEFT JOIN files_index f ON f.tape_label=w.tape_label
               LEFT JOIN archive_bundles b ON b.bundle_id=f.bundle_id
               WHERE f.file_id IS NULL OR NOT EXISTS (
                   SELECT 1 FROM bundle_paths bp
                   WHERE bp.tape_label=w.tape_label
                     AND bp.stored_bundle_path=b.tape_path
               )
               GROUP BY w.tape_label
           ),
           directory_bundle_bytes AS (
               SELECT w.tape_label,
                      COALESCE(SUM(db.byte_count), 0) AS n
               FROM wanted w
               LEFT JOIN directory_archive_bundles db
                 ON db.tape_label=w.tape_label
               GROUP BY w.tape_label
           )
           SELECT w.tape_label,
                  COALESCE(l.n, 0) + COALESCE(d.n, 0) AS used
           FROM wanted w
           LEFT JOIN legacy_file_bytes l ON l.tape_label=w.tape_label
           LEFT JOIN directory_bundle_bytes d ON d.tape_label=w.tape_label""",
        (labels, labels),
    ).fetchall()
    return {row["tape_label"]: int(row["used"] or 0) for row in rows}


def remove_migrated_hot_rows(hot_conninfo, cfg, migration_id, *,
                             hot_backup_path, cold_backup_path,
                             cold_backup_verified, execute=False,
                             governor=None):
    _resource_check(governor, "hot small-row removal")
    if execute and (not hot_backup_path or not cold_backup_path):
        raise RuntimeError(
            "[COLD] Verified hot and cold backup paths are required.")
    if execute and not cold_backup_verified:
        raise RuntimeError("[COLD] Cold DB backup verification is required.")
    batch_rows = int(cfg.cold_batch_rows)
    with _connect(hot_conninfo) as conn:
        ensure_hot_schema(conn)
        migration = _migration_row(conn, migration_id)
        if not migration:
            raise RuntimeError(f"[COLD] Migration not found: {migration_id}")
        if not migration["validation_passed"]:
            raise RuntimeError(
                f"[COLD] Migration {migration_id} has not passed validation.")
        source_id_column = migration["source_hot_id_column"]
        if not source_id_column:
            raise RuntimeError(
                "[COLD] Migration has no stable source ID column; refusing delete.")

        summary = conn.execute(
            """SELECT COUNT(*) AS snapshot_rows,
                      SUM(CASE WHEN covered_by_hot_accounting THEN 1 ELSE 0 END) AS removable_rows,
                      SUM(CASE WHEN NOT covered_by_hot_accounting THEN 1 ELSE 0 END) AS skipped_rows,
                      COALESCE(SUM(CASE WHEN covered_by_hot_accounting
                                        THEN file_size_bytes ELSE 0 END), 0) AS removable_bytes
               FROM small_file_cold_migration_sources
               WHERE migration_id=%s AND source_hot_table='files_index'""",
            (migration_id,),
        ).fetchone()
        tapes = [
            row["tape_label"] for row in conn.execute(
                """SELECT DISTINCT tape_label
                   FROM small_file_cold_migration_sources
                   WHERE migration_id=%s""",
                (migration_id,),
            ).fetchall()
        ]
        before = _used_space_by_tape(conn, tapes)
        report = {
            "migration_id": int(migration_id),
            "mode": "execute" if execute else "dry-run",
            "hot_backup_path": str(hot_backup_path or ""),
            "cold_backup_path": str(cold_backup_path or ""),
            "cold_backup_verified": bool(cold_backup_verified),
            "snapshot_rows": int(summary["snapshot_rows"] or 0),
            "eligible_delete_rows": int(summary["removable_rows"] or 0),
            "skipped_rows": int(summary["skipped_rows"] or 0),
            "eligible_delete_bytes": int(summary["removable_bytes"] or 0),
            "deleted_rows": 0,
            "deleted_bytes": 0,
            "per_tape_accounting": {"before": before, "after": before},
        }
        if not execute:
            conn.rollback()
            return report

        deleted_rows = 0
        deleted_bytes = 0
        # Close the implicit read transaction so the delete block below is a
        # real outermost transaction (not a SAVEPOINT) — see execute_migration.
        conn.commit()
        with conn.transaction():
            conn.execute(
                """CREATE TEMP TABLE _cold_delete_ids ON COMMIT DROP AS
                   SELECT s.source_hot_row_id, s.file_size_bytes
                   FROM small_file_cold_migration_sources s
                   JOIN files_index f ON f.file_id=s.source_hot_row_id
                    AND f.file_size_bytes=s.file_size_bytes
                   WHERE s.migration_id=%s
                     AND s.source_hot_table='files_index'
                     AND s.covered_by_hot_accounting""",
                (migration_id,),
            )
            conn.execute(
                "CREATE INDEX ON _cold_delete_ids(source_hot_row_id)")
            while True:
                _resource_check(governor, "hot small-row delete batch")
                row = conn.execute(
                    """WITH batch AS (
                           SELECT source_hot_row_id
                           FROM _cold_delete_ids
                           LIMIT %s
                       ),
                       deleted AS (
                           DELETE FROM files_index f
                           USING batch b
                           WHERE f.file_id=b.source_hot_row_id
                           RETURNING f.file_size_bytes
                       ),
                       removed_ids AS (
                           DELETE FROM _cold_delete_ids t
                           USING batch b
                           WHERE t.source_hot_row_id=b.source_hot_row_id
                           RETURNING 1
                       )
                       SELECT
                           (SELECT COUNT(*) FROM removed_ids) AS ids_removed,
                           (SELECT COUNT(*) FROM deleted) AS rows_deleted,
                           (SELECT COALESCE(SUM(file_size_bytes), 0)
                            FROM deleted) AS bytes_deleted""",
                    (batch_rows,),
                ).fetchone()
                if int(row["ids_removed"] or 0) == 0:
                    break
                deleted_rows += int(row["rows_deleted"] or 0)
                deleted_bytes += int(row["bytes_deleted"] or 0)
            after = _used_space_by_tape(conn, tapes)
            report["deleted_rows"] = deleted_rows
            report["deleted_bytes"] = deleted_bytes
            report["per_tape_accounting"] = {
                "before": before,
                "after": after,
                "passed": before == after,
            }
            if before != after:
                raise RuntimeError(
                    "[COLD] Per-tape used-space regression failed; "
                    "hot-row deletion was rolled back.")
            conn.execute(
                """UPDATE small_file_cold_migrations
                   SET status='hot_rows_removed',
                       cold_backup_path=%s,
                       cold_backup_verified=%s,
                       removal_report=%s,
                       finished_at=now()
                   WHERE migration_id=%s""",
                (str(cold_backup_path), bool(cold_backup_verified),
                 json.dumps(report), migration_id),
            )
        conn.execute("ANALYZE files_index")
        conn.commit()
        return report


def search_cold(cold_conninfo_value, query, *, limit=100, fetch_rows=5000,
                governor=None):
    _resource_check(governor, "cold search")
    # Escape LIKE metacharacters so a literal '_'/'%' in the query matches
    # itself (same rule as the hot catalog search); keep the read path free
    # of DDL so searching never requires schema privileges.
    needle = f"%{escape_like_literal(query)}%"
    limit = max(1, int(limit or 100))
    with _connect(cold_conninfo_value) as conn:
        if not _table_exists(conn, COLD_PAYLOAD_TABLE):
            raise RuntimeError(
                "[COLD] Cold manifest table does not exist yet; run a cold "
                "migration first.")
        with conn.cursor(name="cold_search") as cur:
            cur.itersize = fetch_rows
            cur.execute(
                f"""SELECT migration_id, source_hot_row_id, source_host,
                           tape_label, stored_bundle_path, relative_path,
                           file_name, size_bytes, source_kind, loaded_at
                    FROM {COLD_PAYLOAD_TABLE}
                    WHERE file_name ILIKE %s ESCAPE '\\'
                       OR relative_path ILIKE %s ESCAPE '\\'
                    LIMIT %s""",
                (needle, needle, limit),
            )
            rows = []
            while True:
                _resource_check(governor, "cold search fetch")
                chunk = cur.fetchmany(fetch_rows)
                if not chunk:
                    break
                rows.extend(dict(row) for row in chunk)
                if len(rows) >= limit:
                    return rows[:limit]
            return rows


def backup_is_after_validation(backup_path, validated_at):
    if not backup_path or validated_at is None:
        return False
    try:
        mtime = os.path.getmtime(backup_path)
    except OSError:
        return False
    if validated_at.tzinfo is None:
        validated_at = validated_at.replace(tzinfo=timezone.utc)
    return mtime >= validated_at.timestamp()


def migration_status(hot_conninfo):
    with _connect(hot_conninfo, autocommit=True) as conn:
        # Read-only path: no DDL. A fresh database simply has no migrations.
        if not _table_exists(conn, "small_file_cold_migrations"):
            return []
        rows = conn.execute(
            """SELECT migration_id, threshold_bytes, hot_db_name, cold_db_name,
                      status, eligible_rows, copied_rows, validated_rows,
                      validation_passed, started_at, validated_at, finished_at,
                      error_message
               FROM small_file_cold_migrations
               ORDER BY migration_id DESC
               LIMIT 20"""
        ).fetchall()
        return [dict(row) for row in rows]


def migration_info(hot_conninfo, migration_id):
    with _connect(hot_conninfo, autocommit=True) as conn:
        # Read-only path: no DDL.
        if not _table_exists(conn, "small_file_cold_migrations"):
            return None
        row = _migration_row(conn, migration_id)
        return dict(row) if row else None
